apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: geargo
    component: database
spec:
  selector:
    app: geargo
    component: database
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
  type: ClusterIP
